apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: app-deployment
        image: veluprabhakaranv/simplenodeapp:latest
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3002
        
# service type loadbalancer       
---

apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: harness-cicd
spec:
  ports:
    - port: 3002
  type: LoadBalancer
  selector:
    app: node-app
